In [2]:
import requests
from bs4 import BeautifulSoup
from collections import defaultdict
import pandas as pd

In [33]:
# Collect and parse first page
url = 'https://www.ebay.com/sch/i.html?_from=R40&_nkw=prizm+silver+psa10+basketball&_sacat=0&_sop=10&_ipg=200&_pgn='
pageNum = 1
data = defaultdict(list)

In [34]:
for pageNum in range(1, 100):
    page = requests.get(url+str(pageNum))
    soup = BeautifulSoup(page.text, 'html.parser')
    items = soup.findAll(class_='s-item__details clearfix')
    print(r"Page "+str(pageNum)+r": "+str(len(items)))
    for item in items:
        time = item.find(class_='s-item__listingDate').contents[0].contents[0]
        data["Time"].append(time)
        price = item.find(class_='s-item__price').contents[0]
        try:
            price = price.contents[0]
        except BaseException:
            pass
        price = float(str(price).replace("$", "").replace(",", ""))
        data["Price"].append(price)

Page 1: 202
Page 2: 200
Page 3: 200
Page 4: 200
Page 5: 200
Page 6: 200
Page 7: 200
Page 8: 200
Page 9: 200
Page 10: 200
Page 11: 200
Page 12: 80
Page 13: 79
Page 14: 77
Page 15: 79
Page 16: 78
Page 17: 79
Page 18: 80
Page 19: 80
Page 20: 80
Page 21: 80
Page 22: 78
Page 23: 78
Page 24: 78
Page 25: 74
Page 26: 79
Page 27: 80
Page 28: 77
Page 29: 79
Page 30: 79
Page 31: 79
Page 32: 79
Page 33: 80
Page 34: 79
Page 35: 79
Page 36: 78
Page 37: 79
Page 38: 79
Page 39: 79
Page 40: 79
Page 41: 79
Page 42: 78
Page 43: 79
Page 44: 79
Page 45: 79
Page 46: 78
Page 47: 73
Page 48: 79
Page 49: 78
Page 50: 78
Page 51: 79
Page 52: 79
Page 53: 79
Page 54: 77
Page 55: 79
Page 56: 79
Page 57: 76
Page 58: 79
Page 59: 79
Page 60: 78
Page 61: 79
Page 62: 79
Page 63: 77
Page 64: 79
Page 65: 76
Page 66: 78
Page 67: 79
Page 68: 79
Page 69: 79
Page 70: 74
Page 71: 77
Page 72: 78
Page 73: 69
Page 74: 78
Page 75: 77
Page 76: 74
Page 77: 0
Page 78: 0
Page 79: 0
Page 80: 0
Page 81: 0
Page 82: 0
Page 83: 0
Page 84: 0
Page 85: 0
Page 86: 0
Page 87: 0
Page 88: 0
Page 89: 0
Page 90: 0
Page 91: 0
Page 92: 0
Page 93: 0
Page 94: 0
Page 95: 0
Page 96: 0
Page 97: 0
Page 98: 0
Page 99: 0

In [3]:
url_partA = 'https://www.ebay.com/sch/i.html?_from=R40&_sacat=0&LH_Sold=1&_udlo=&_udhi=&_samilow=&_samihi=&_sadis=15&_stpos=07014&_sop=10&_dmd=1&LH_Complete=1&_fosrp=1&_nkw=prizm+silver+psa10+basketball&_pgn='
url_partB = '&_skc=200&rt=nc'

In [59]:
data_0313 = defaultdict(list)
pageNum = 2
url = url_partA + str(pageNum) + url_partB
page = requests.get(url+str(pageNum))
soup = BeautifulSoup(page.text, 'html.parser')
items = soup.findAll(class_='sresult lvresult clearfix li')
print(r"Page "+str(pageNum)+r": "+str(len(items)))

Page 2: 50

In [60]:
for item in items:
    title = item.find(class_='lvtitle').contents[0].contents[0]
    data_0313["Title"].append(title)
    print(title)
    temp_price_list = item.find(class_='lvprice prc').contents[1].contents
    price = temp_price_list[0] if len(temp_price_list) == 1 else temp_price_list[1].contents[0]
    time = item.find(class_='tme').contents[1].contents[0]
    data_0313["Time"].append(time)
    price = float(str(price).replace("$", "").replace(",", ""))
    data_0313["Price"].append(price)

INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER PRIZM RC #280 PSA 10 GEM MINT
OKARO WHITE - 2017/18 PANINI PRIZM - ROOKIE - #52 - SILVER REFRACTOR PSA 10 PMJS
2018 Panini Prizm #62 Jamal Murray Silver PRIZM PSA 10 GEM MT Denver Nuggets
2016-17 Panini Prizm Jaylen Brown Silver Rookie Refractor RC #44 Gem Mint PSA 10
2018 Panini Prizm Basketball Silver #62 Jamal Murray Denver Nuggets PSA 10
Lonnie Walker Rookie Silver Prizm 2018-19 Spurs Rc Sp PSA 10 Gem Mint No. 251
2017-18 Panini Prizm TJ Leaf Silver Prizm PSA 10 Gem Mint PMJS
2018 PANINI PRIZM 228 JARRETT ALLEN SILVER PRIZM BROOKLYN NETS PSA 10
2019-20 Panini Prizm JARRETT CULVER Silver Prizm Refractor PSA 10! RC
2017 Panini Prizm Silver Prizms #289 Lonzo Ball PSA 10 GEM MT Los Angeles Lakers
2012-2013 PRIZM STEPHEN CURRY SILVER REFRACTOR PSA 10 GEM MINT WARRIORS
Trae Young 2018-19 Donruss Optic Holo Silver Prizm Rookie RC PSA 10 GEM MINT🔥🔥
(1) 2017-18 Panini Prizm Frank Ntilikina Rookie Silver Prizm Knicks RC PSA 10
TRAE YOUNG 2018-19 PRIZM LUCK OF THE LOTTERY SILVER REFRACTOR RC PSA 10 **HOT**
2018-19 Panini Prizm Silver Freshman Phenoms Trae Young Rookie RC #21, PSA 10
BAM ADEBAYO 2017 PANINI PRIZM SILVER PRIZMS RC SSP #51 PSA 10 GEM MINT
2018-19 Donruss Optic Holo Silver Prizm Shai Gilgeous-Alexa
2018 Panini Prizm Freshmen Phenoms Silver #23 Luka Doncic PSA 10 GEM MINT RC
2019-20 Prizm Zion Williamson Rc Rookie Silver PSA 10 Gem Mint - Pelicans 🔥🔥🔥
2018 Panini Prizm Freshman Phenoms Silver #23 Luka Doncic PSA 10 GEM MINT RC
2017-18 Panini Prizm Silver Zach Collins Auto Trail Blazers PSA 10 #144 RC
2018-19 Panini Prizm Silver Donovan Mitchell #143 PSA 10 GEM MT Utah Jazz
2019-20 Panini Prizm Silver #248 Zion Williamson RC Rookie PSA 10 CENTERED
2017-18 Panini Prizm Silver Zach Collins Auto Trail Blazers PSA 10 #144 RC
2019-20 Panini Prizm Silver Get Hyped Lebron James #2 La Lakers PSA 10 Gem Mint
2018-19 Panini Prizm Jaren Jackson Jr. Silver Rookie RC PSA 10 #66 Grizzlies SP
2018-19 Panini Prizm Basketball #296 Giannis Antetokounmpo Silver Prizms PSA 10
2017 PANINI PRIZM DERRICK WHITE SILVER PRIZM #298 PSA 10 GEM MINT
2018/19 PRIZM Silver Luka Doncic #280 PSA 10
2017 PANINI PRIZM DERRICK WHITE SILVER PRIZM #298 PSA 10 GEM MINT
2016-17 Panini Prizm Silver Giannis Antetokounmpo Milwaukee Bucks PSA 10
2018 Panini Prizm Emergent Silver #3 Luka Doncic PSA 10 GEM MINT RC
TRAE YOUNG PSA 10 2018 PANINI PRIZM BASKETBALL #78 SILVER ROOKIE RC HAWKS 2647
TRAE YOUNG PSA 10 2018 PANINI PRIZM BASKETBALL #78 SILVER ROOKIE RC HAWKS 6666
Lot of (2) 2018-19 Panini Prizm TROY BROWN JR. Silver Prizm PSA 10 Gem Mint!
AARON HOLIDAY 2018-19 PRIZM SILVER REF ROOKIE RC #114 PSA 10 GEM MINT PACERS! $^
2018 TRAE YOUNG PANINI PRIZM RC FAST BREAK Silver PRIZM PSA 10 GEM Rookie Sp HOT
2018 PRIZM TRAE YOUNG SP RC SILVER PRIZM EMERGENT PSA 10 GEM MINT HAWKS HOT!
Trae Young Silver Prizm Rookie PSA 10
Jayson tatum prizm rookie silver psa 10
(2) 2017-18 Panini Prizm Frank Ntilikina Rookie Silver Prizm Knicks RC PSA 10
(1) 2017-18 Panini Prizm Frank Ntilikina Rookie Silver Prizm Knicks RC PSA 10
PSA 10 2017-18 Panini Prizm Silver Giannis Antetokounmpo #182
Giannis Antetokounmpo 2018-19 Panini Prizm Silver #296 PSA 10 Gem Mint Bucks
2017 JOSH JACKSON PANINI PRIZM SILVER ROOKIE RC LOT PSA 10 BGS 9.5 GEM MINT 💎
Luka Doncic 2018 Panini Prizm SILVER Rookie Rc GEM MINT PSA 10 Dallas Mavericks
PSA 10 2018-19 Panini Prizm Silver Giannis Antetokounmpo #296
2018-19 Panini Prizm Trae Young Silver Prizm Rookie RC PSA 10 GEM MINT SP Hawks
2018-2019 Panini Prizm Basketball Trae Young Base Non Silver PSA 10 Gem Mint RC
💎 2017 Josh Jackson Prizm Mosaic Silver Refractor ROOKIE RC AUTO PSA 10 Gem 💎

In [55]:
raw_0313 = pd.DataFrame(data_0313)
raw_0313.set_index("Time").sort_index()

                Price                                              Title
Time
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:37    60.00  2017-18 Panini Prizm Silver Prizms Frank Ntili...
Mar-11 10:42    49.95  💎 2017 Josh Jackson Prizm Mosaic Silver Refrac...
Mar-11 10:42    49.95  💎 2017 Josh Jackson Prizm Mosaic Silver Refrac...
Mar-11 10:42    49.95  💎 2017 Josh Jackson Prizm Mosaic Silver Refrac...
Mar-11 10:42    49.95  💎 2017 Josh Jackson Prizm Mosaic Silver Refrac...
Mar-11 10:42    49.95  💎 2017 Josh Jackson Prizm Mosaic Silver Refrac...
Mar-11 10:42    49.95  💎 2017 Josh Jackson Prizm Mosaic Silver Refrac...
...               ...                                                ...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...
Mar-11 18:24  1999.00  INVEST NOW!!! 2018 PANINI LUKA DONCIC SILVER P...

[4950 rows x 2 columns]

----

In [137]:
raw = pd.DataFrame(data)
raw.head()

     Price         Time
0    75.00  Mar-6 07:55
1   699.00  Mar-6 07:49
2   199.99  Mar-3 17:45
3  2499.99  Jan-4 11:44
4   899.99  Mar-6 07:47

In [144]:
raw.set_index("Time").to_csv(r"raw_sports_cards.csv")

In [145]:
month_dict = {"Jan": 1, "Feb": 2, "Mar": 3, "Apr": 4, "May": 5, "Jun": 6, 
              "Jul": 7, "Aug": 8, "Sep": 9, "Oct": 10, "Nov": 11, "Dec": 12}
year = 2020
prev_month = 3

def cleanup_date(raw_date):
    
    global month_dict, year, prev_month
    
    raw = str(raw_date)
    date, time = raw.split(' ')
    month, day = date.split('-')
    hour, minute = time.split(':')
    
    month = month_dict[month]
    
    if month == 12 and prev_month != 12:
        year -= 1
    try:
        result = pd.Period(month=month, year=year, freq='T',
                           day=int(day), hour=int(hour), minute=int(minute))
    except BaseException as e:
        print(e)
        print(raw)
        
    prev_month = month
    return result

In [146]:
raw["Time"] = raw["Time"].apply(cleanup_date)

In [150]:
raw.set_index("Time").to_csv(r"clean_sports_cards.csv")